version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-ui
#    hostname: rabbitmq-ui
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
#Prod only      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
#    volumes:
#Persist rabbit files on host      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672